// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUO-5gRBErjAUQHsmapipdyyPIkWxDSs',
    appId: '1:901639115352:web:e914c705d4a00a4477b02d',
    messagingSenderId: '901639115352',
    projectId: 'ev-life-db',
    authDomain: 'ev-life-db.firebaseapp.com',
    storageBucket: 'ev-life-db.appspot.com',
    measurementId: 'G-3Y2X1VPJZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSPDFEn-E3D9HQtv0XgGT6se7tEkloO8',
    appId: '1:901639115352:android:17fecf90d68fe1fb77b02d',
    messagingSenderId: '901639115352',
    projectId: 'ev-life-db',
    storageBucket: 'ev-life-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRPna7PLP82h7HGRHewnKrou0Vb5LaBg',
    appId: '1:901639115352:ios:a12b8c5ea7bfbb0077b02d',
    messagingSenderId: '901639115352',
    projectId: 'ev-life-db',
    storageBucket: 'ev-life-db.appspot.com',
    iosClientId: '901639115352-lsdi45fh0hsp4udms5hsllr6kj2vpgkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.theEvLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnRPna7PLP82h7HGRHewnKrou0Vb5LaBg',
    appId: '1:901639115352:ios:51a1502d20105b0777b02d',
    messagingSenderId: '901639115352',
    projectId: 'ev-life-db',
    storageBucket: 'ev-life-db.appspot.com',
    iosClientId: '901639115352-7m98c3hmg96qkqmlk9ku770kjmblpbef.apps.googleusercontent.com',
    iosBundleId: 'com.example.theEvLife.RunnerTests',
  );
}
